// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIhOU6EIrX40zlCivbKXxe24y3D8VJEoE',
    appId: '1:675445824557:android:36d15d05f84a6112916ca4',
    messagingSenderId: '675445824557',
    projectId: 'qi-app-4edde',
    storageBucket: 'qi-app-4edde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAajgbqtC5D-9tsxcT2TpPnbvSBxRmFET0',
    appId: '1:675445824557:ios:2821733227e378b8916ca4',
    messagingSenderId: '675445824557',
    projectId: 'qi-app-4edde',
    storageBucket: 'qi-app-4edde.firebasestorage.app',
    androidClientId: '675445824557-lul25qcfo9quurj00privqnngajft895.apps.googleusercontent.com',
    iosClientId: '675445824557-nj9me4qi8j2hn6t0h3v12krsntggbr1n.apps.googleusercontent.com',
    iosBundleId: 'com.qifoodfocus.app',
  );
}
